### ISSUE TITLE
Outage of servers 27 May 2017

### ISSUE THREAD

**Issue by christopherreay** [visual-tools/project-management#1]
Until the current issues with communication within the group are resolved, I see no reason that I should maintain paying for servers, where everybody else is working in a black box, and I am not able to leverage the results of their work.

Im available on Slack or Here at any time

Servers will be out from Monday 29th at the current "status quo"

**Comment by johnkellas** [comment]
Documents being edited and are available to current team members (and other on request) in Google drive folder https://drive.google.com/drive/folders/0B2ExtwsWVr9Dc1dteGZpaWtGREk?usp=sharing

**Comment by christopherreay** [comment]
Issue closed in expectation of improved self documentation
