### ISSUE TITLE
Blog post RSA Late May 2017

### ISSUE THREAD

**Issue by christopherreay** [visual-tools/project-management#11]
https://docs.google.com/document/d/1vKOThhIdY1qpjLqJ2n7PeUePKAPJz56H0nmvV9KADig/edit?disco=AAAABLMzuPM&usp=comment_email_document

**Comment by christopherreay** [comment]
@johnkellas I think this is good now

**Comment by johnkellas** [comment]
Agreed

**Comment by christopherreay** [comment]
paste a link and close the issue when its up. If you wanted to create a box for the RSA, we could share all the emails. No hurry on that. Maybe We can have a "publishing" streak pipeline

**Comment by johnkellas** [comment]
https://www.thersa.org/discover/publications-and-articles/rsa-blogs/2017/05/see-what-they-mean
